// Code generated by goyacc -p yr -o parser/parser.go parser/grammar.y. DO NOT EDIT.

//line parser/grammar.y:31
package parser

import __yyfmt__ "fmt"

//line parser/grammar.y:31

import (
	"github.com/secDre4mer/gyp/ast"
	gyperror "github.com/secDre4mer/gyp/error"
	"strings"
)

type modifiers uint64

const (
	_                   = iota // ignore first value by assigning to blank identifier
	ModGlobal modifiers = 1 << iota
	ModPrivate
	ModASCII
	ModWide
	ModXor
	ModFullword
	ModNocase
	ModBase64
	ModBase64Wide
)

type stringModifiers struct {
	modifiers
	XorMin         int32
	XorMax         int32
	Base64Alphabet string
}

//line parser/grammar.y:183
type yrSymType struct {
	yys       int
	i64       int64
	f64       float64
	s         string
	ss        []string
	reg       *ast.LiteralRegexp
	hexTokens []ast.HexToken
	mod       modifiers
	smod      stringModifiers
	rule      *ast.Rule
	meta      *ast.Meta
	metas     []*ast.Meta
	ys        ast.String
	yss       []ast.String
	node      ast.Node
	nodes     []ast.Node
	rng       *ast.Range
	expr      ast.Expression
	exprs     []ast.Expression
	si        *ast.StringIdentifier
	sis       []*ast.StringIdentifier
	ident     *ast.Identifier

	// lineno is not a symbol type, it's the line number where the symbol
	// appears in the source file. This is a little hack used for passing
	// the line number where each token appears from the lexer to the parser.
	// This relies on the fact that Go doesn't implement unions, and therefore
	// goyacc actually uses a struct for passing around symbol values. Being
	// a struct those values can contain both the value itself (in some of
	// the fields listed above) and the line number. This wouldn't work with
	// C code produced by yacc, as this would be a union instead of a struct.
	//
	// This can be used within rule actions as:
	//
	//  lineNumber := $<lineno>1
	//
	// In the example lineNumber will hold the line number for the first
	// symbol in the production rule. The value for the symbol itself would
	// be $1 as usual. Similarly $<lineno>N will return the line number for
	// the N-th symbol in the production rule.

	lineno int
}

const _END_OF_INCLUDED_FILE_ = 57346
const _DOT_DOT_ = 57347
const _RULE_ = 57348
const _PRIVATE_ = 57349
const _GLOBAL_ = 57350
const _META_ = 57351
const _STRINGS_ = 57352
const _CONDITION_ = 57353
const _IDENTIFIER_ = 57354
const _STRING_IDENTIFIER_ = 57355
const _STRING_COUNT_ = 57356
const _STRING_OFFSET_ = 57357
const _STRING_LENGTH_ = 57358
const _STRING_IDENTIFIER_WITH_WILDCARD_ = 57359
const _DECIMAL_NUMBER_ = 57360
const _HEX_NUMBER_ = 57361
const _OCT_NUMBER_ = 57362
const _DOUBLE_ = 57363
const _INTEGER_FUNCTION_ = 57364
const _TEXT_STRING_ = 57365
const _HEX_STRING_ = 57366
const _REGEXP_ = 57367
const _ASCII_ = 57368
const _WIDE_ = 57369
const _XOR_ = 57370
const _NOCASE_ = 57371
const _FULLWORD_ = 57372
const _BASE64_ = 57373
const _BASE64WIDE_ = 57374
const _AT_ = 57375
const _FILESIZE_ = 57376
const _ENTRYPOINT_ = 57377
const _ALL_ = 57378
const _ANY_ = 57379
const _NONE_ = 57380
const _IN_ = 57381
const _OF_ = 57382
const _FOR_ = 57383
const _THEM_ = 57384
const _MATCHES_ = 57385
const _CONTAINS_ = 57386
const _ICONTAINS_ = 57387
const _STARTSWITH_ = 57388
const _ISTARTSWITH_ = 57389
const _ENDSWITH_ = 57390
const _IENDSWITH_ = 57391
const _IEQUALS_ = 57392
const _IMPORT_ = 57393
const _TRUE_ = 57394
const _FALSE_ = 57395
const _INCLUDE_ = 57396
const _DEFINED_ = 57397
const _OR_ = 57398
const _AND_ = 57399
const _NOT_ = 57400
const _EQ_ = 57401
const _NEQ_ = 57402
const _LT_ = 57403
const _LE_ = 57404
const _GT_ = 57405
const _GE_ = 57406
const _SHIFT_LEFT_ = 57407
const _SHIFT_RIGHT_ = 57408
const UNARY_MINUS = 57409

var yrToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"_END_OF_INCLUDED_FILE_",
	"_DOT_DOT_",
	"_RULE_",
	"_PRIVATE_",
	"_GLOBAL_",
	"_META_",
	"_STRINGS_",
	"_CONDITION_",
	"_IDENTIFIER_",
	"_STRING_IDENTIFIER_",
	"_STRING_COUNT_",
	"_STRING_OFFSET_",
	"_STRING_LENGTH_",
	"_STRING_IDENTIFIER_WITH_WILDCARD_",
	"_DECIMAL_NUMBER_",
	"_HEX_NUMBER_",
	"_OCT_NUMBER_",
	"_DOUBLE_",
	"_INTEGER_FUNCTION_",
	"_TEXT_STRING_",
	"_HEX_STRING_",
	"_REGEXP_",
	"_ASCII_",
	"_WIDE_",
	"_XOR_",
	"_NOCASE_",
	"_FULLWORD_",
	"_BASE64_",
	"_BASE64WIDE_",
	"_AT_",
	"_FILESIZE_",
	"_ENTRYPOINT_",
	"_ALL_",
	"_ANY_",
	"_NONE_",
	"_IN_",
	"_OF_",
	"_FOR_",
	"_THEM_",
	"_MATCHES_",
	"_CONTAINS_",
	"_ICONTAINS_",
	"_STARTSWITH_",
	"_ISTARTSWITH_",
	"_ENDSWITH_",
	"_IENDSWITH_",
	"_IEQUALS_",
	"_IMPORT_",
	"_TRUE_",
	"_FALSE_",
	"_INCLUDE_",
	"_DEFINED_",
	"_OR_",
	"_AND_",
	"_NOT_",
	"'|'",
	"'^'",
	"'&'",
	"_EQ_",
	"_NEQ_",
	"_LT_",
	"_LE_",
	"_GT_",
	"_GE_",
	"_SHIFT_LEFT_",
	"_SHIFT_RIGHT_",
	"'+'",
	"'-'",
	"'*'",
	"'\\\\'",
	"'%'",
	"'~'",
	"UNARY_MINUS",
	"'{'",
	"'}'",
	"':'",
	"'='",
	"'('",
	"')'",
	"'.'",
	"'['",
	"']'",
	"','",
}

var yrStatenames = [...]string{}

const yrEofCode = 1
const yrErrCode = 2
const yrInitialStackSize = 16

//line parser/grammar.y:1564

// This function takes an operator and two operands and returns a Expression
// representing the operation. If the left operand is an operation of the
// the same kind than the specified by the operator, the right operand is
// simply appended to that existing operation. This implies that the operator
// must be left-associative in order to be used with this function.
func operation(operator ast.OperatorType, left, right ast.Expression) (n ast.Expression) {
	if operation, ok := left.(*ast.Operation); ok && operation.Operator == operator {
		operation.Operands = append(operation.Operands, right)
		n = operation
	} else {
		n = &ast.Operation{
			Operator: operator,
			Operands: []ast.Expression{left, right},
		}
	}
	return n
}

//line yacctab:1
var yrExca = [...]int16{
	-1, 1,
	1, -1,
	-2, 15,
	-1, 55,
	40, 124,
	-2, 102,
	-1, 121,
	40, 124,
	-2, 102,
	-1, 185,
	82, 66,
	86, 66,
	-2, 69,
	-1, 247,
	82, 67,
	86, 67,
	-2, 69,
}

const yrPrivate = 57344

const yrLast = 506

var yrAct = [...]int16{
	55, 44, 210, 209, 208, 52, 163, 73, 170, 171,
	199, 220, 88, 89, 90, 91, 92, 93, 94, 95,
	264, 244, 242, 276, 265, 245, 243, 122, 109, 107,
	108, 101, 102, 97, 99, 98, 100, 110, 111, 103,
	104, 105, 106, 96, 76, 240, 126, 85, 125, 241,
	270, 176, 268, 129, 80, 127, 128, 200, 115, 87,
	86, 269, 121, 87, 86, 267, 219, 120, 51, 109,
	107, 108, 175, 263, 255, 130, 131, 174, 110, 111,
	103, 104, 105, 106, 168, 275, 174, 118, 119, 273,
	138, 139, 140, 141, 142, 143, 144, 146, 147, 148,
	149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
	159, 160, 161, 162, 135, 136, 202, 169, 250, 249,
	248, 164, 174, 234, 177, 197, 179, 180, 123, 182,
	42, 178, 38, 137, 80, 185, 70, 71, 72, 252,
	65, 66, 67, 68, 64, 69, 237, 81, 40, 28,
	26, 17, 39, 18, 195, 196, 62, 63, 77, 78,
	79, 173, 105, 106, 168, 198, 246, 58, 124, 146,
	109, 107, 108, 87, 86, 201, 86, 117, 30, 110,
	111, 103, 104, 105, 106, 168, 110, 111, 103, 104,
	105, 106, 168, 74, 5, 167, 218, 75, 103, 104,
	105, 106, 168, 116, 81, 239, 235, 232, 37, 260,
	238, 80, 259, 70, 71, 72, 35, 65, 66, 67,
	68, 64, 69, 166, 81, 114, 247, 213, 211, 214,
	204, 251, 212, 62, 63, 254, 203, 112, 214, 145,
	13, 7, 8, 113, 4, 211, 256, 257, 258, 212,
	36, 41, 261, 213, 80, 236, 70, 71, 72, 192,
	65, 66, 67, 68, 64, 69, 272, 81, 213, 211,
	74, 181, 274, 212, 75, 31, 62, 63, 189, 188,
	116, 190, 191, 266, 23, 20, 80, 56, 70, 71,
	72, 271, 65, 66, 67, 68, 64, 69, 14, 81,
	48, 49, 50, 33, 25, 43, 22, 194, 62, 63,
	77, 78, 79, 74, 132, 57, 27, 75, 82, 84,
	83, 15, 1, 116, 207, 172, 53, 54, 206, 60,
	107, 108, 59, 205, 46, 47, 165, 233, 110, 111,
	103, 104, 105, 106, 168, 74, 226, 231, 253, 75,
	48, 49, 50, 45, 183, 61, 88, 89, 90, 91,
	92, 93, 94, 95, 184, 223, 222, 229, 224, 225,
	227, 228, 109, 107, 108, 101, 102, 97, 99, 98,
	100, 110, 111, 103, 104, 105, 106, 96, 109, 107,
	108, 9, 11, 12, 32, 6, 10, 110, 111, 103,
	104, 105, 106, 168, 134, 193, 109, 107, 108, 133,
	187, 186, 221, 34, 217, 110, 111, 103, 104, 105,
	106, 168, 230, 24, 109, 107, 108, 21, 29, 19,
	16, 2, 216, 110, 111, 103, 104, 105, 106, 168,
	109, 107, 108, 3, 0, 0, 0, 262, 0, 110,
	111, 103, 104, 105, 106, 168, 109, 107, 108, 0,
	0, 0, 0, 215, 0, 110, 111, 103, 104, 105,
	106, 168, 0, 0, 0, 0, 109, 107, 108, 176,
	0, 0, 0, 0, 0, 110, 111, 103, 104, 105,
	106, 168, 108, 0, 0, 0, 0, 0, 0, 110,
	111, 103, 104, 105, 106, 168,
}

var yrPact = [...]int16{
	-1000, 190, -1000, -1000, 219, -1000, 385, 217, -1000, 286,
	-1000, -1000, -1000, -1000, -1000, 72, 76, 273, 297, 272,
	-1000, 294, 71, -1000, -1000, 70, 263, 292, 237, 263,
	-1000, 52, 74, 69, 237, -1000, 50, -1000, 282, -1000,
	274, -1000, 295, -1000, -1000, 332, -1000, -1000, -1000, -1000,
	-1000, 117, -1000, -1000, -1000, 313, 204, 122, 137, 274,
	274, 274, -1000, -1000, 47, -1000, -1000, -1000, -1000, -1000,
	129, -36, -38, -28, 242, 242, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 274, 274, 179, 242,
	242, 242, 242, 242, 242, 242, 199, 242, 242, 242,
	242, 242, 242, 242, 242, 242, 242, 242, 242, 242,
	242, 242, 242, 40, 183, 10, 242, 80, -1000, -1000,
	-10, -31, 117, 242, 40, 242, 242, 259, 242, 274,
	-1000, -1000, -1000, 252, 300, -1000, 119, -1000, 10, 10,
	10, 10, 10, 10, 10, 44, -1000, 10, 10, 10,
	10, 10, 10, 90, 90, -1000, -1000, 431, 118, 270,
	128, 128, 10, -1000, 242, -29, 35, -1000, 242, 397,
	197, -1000, -1000, 215, -1000, -1000, -1000, 381, -1000, 347,
	329, -1000, 111, -16, -75, -1000, 339, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 256, 417, 42,
	243, 67, 232, 40, 242, -37, -60, -61, -1000, -1000,
	-1000, -1000, -1000, 94, -1000, -1000, -1000, -1000, -1000, -1000,
	274, -1000, -1000, -1000, -1000, -1000, -1000, 39, 38, 37,
	242, 60, -28, -1000, 242, -1000, -1000, -7, -1000, 10,
	-1000, 232, -1000, 241, -1000, 206, -1000, -1000, 189, 186,
	332, 365, -8, -62, 417, 274, -1000, -1000, -1000, -17,
	-30, -21, -1000, 274, -1000, 242, 7, -1000, -1000, -1000,
	332, 3, 10, -1000, -59, -1000, -1000,
}

var yrPgo = [...]int16{
	0, 443, 431, 430, 429, 178, 428, 427, 423, 216,
	413, 412, 411, 410, 409, 405, 404, 396, 395, 394,
	5, 27, 0, 7, 364, 354, 167, 348, 347, 337,
	8, 44, 6, 336, 333, 4, 9, 328, 3, 325,
	324, 2, 1, 322, 321, 316, 314,
}

var yrR1 = [...]int8{
	0, 43, 43, 43, 43, 43, 1, 44, 45, 2,
	7, 7, 8, 8, 19, 18, 18, 17, 17, 3,
	3, 4, 4, 6, 6, 5, 5, 5, 5, 5,
	10, 10, 46, 9, 9, 9, 12, 12, 11, 11,
	11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
	14, 14, 13, 13, 13, 13, 13, 16, 16, 15,
	23, 23, 23, 23, 25, 25, 24, 24, 31, 21,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 20, 20, 20, 20, 20, 20,
	20, 20, 20, 20, 29, 29, 32, 27, 27, 30,
	30, 34, 34, 35, 35, 36, 37, 37, 38, 38,
	39, 40, 40, 41, 26, 26, 26, 26, 33, 33,
	28, 28, 42, 42, 42, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22,
}

var yrR2 = [...]int8{
	0, 0, 2, 2, 3, 2, 2, 0, 0, 11,
	0, 3, 0, 3, 3, 0, 2, 1, 1, 0,
	2, 1, 2, 1, 2, 3, 3, 4, 3, 3,
	1, 2, 0, 5, 4, 4, 0, 2, 1, 1,
	1, 1, 1, 1, 1, 4, 4, 1, 4, 6,
	0, 2, 1, 1, 1, 1, 1, 0, 2, 1,
	1, 3, 4, 4, 0, 1, 1, 3, 1, 1,
	1, 1, 3, 3, 3, 3, 3, 3, 3, 3,
	1, 3, 3, 9, 8, 5, 5, 3, 3, 3,
	4, 4, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 1, 3, 3, 1, 5, 1, 3, 3,
	1, 1, 3, 1, 1, 3, 1, 3, 1, 2,
	3, 1, 3, 1, 1, 1, 1, 1, 1, 3,
	1, 1, 1, 1, 1, 3, 1, 1, 4, 1,
	1, 1, 1, 1, 3, 1, 4, 1, 4, 1,
	1, 2, 3, 3, 3, 3, 3, 3, 3, 3,
	2, 3, 3, 1,
}

var yrChk = [...]int16{
	-1000, -43, -2, -1, 54, 4, -18, 51, 23, 6,
	-17, 7, 8, 23, 12, -44, -3, 79, 77, -4,
	12, -7, 9, 12, -8, 10, 79, -45, 79, -6,
	-5, 12, -19, 11, -10, -9, 13, -5, 80, 78,
	79, -9, 80, 23, -42, 71, 52, 53, 18, 19,
	20, -21, -20, 52, 53, -22, 13, 41, -26, 58,
	55, 81, 34, 35, 22, 18, 19, 20, 21, 23,
	14, 15, 16, -23, 71, 75, -31, 36, 37, 38,
	12, 25, 23, 25, 24, -42, 57, 56, 43, 44,
	45, 46, 47, 48, 49, 50, 74, 64, 66, 65,
	67, 62, 63, 70, 71, 72, 73, 60, 61, 59,
	68, 69, 33, 39, -26, -22, 81, 40, -21, -21,
	-20, -22, -21, 81, 39, 84, 84, 83, 84, 81,
	-22, -22, -46, -14, -16, -21, -21, -31, -22, -22,
	-22, -22, -22, -22, -22, 40, -22, -22, -22, -22,
	-22, -22, -22, -22, -22, -22, -22, -22, -22, -22,
	-22, -22, -22, -32, 81, -33, 40, 12, 74, -22,
	-30, -36, -39, 81, 42, 82, 82, -22, -32, -22,
	-22, 12, -22, -25, -24, -20, -12, -13, 27, 26,
	29, 30, 7, -15, 7, -30, -36, 81, -22, 39,
	86, -30, 81, 39, 33, -34, -37, -40, -35, -38,
	-41, 13, 17, 12, 23, 82, 85, 85, 85, 82,
	86, -11, 27, 26, 29, 30, 7, 31, 32, 28,
	5, -28, -23, -29, 81, -32, 12, 79, -32, -22,
	82, 86, 82, 86, 82, 86, 72, -20, 81, 81,
	81, -22, 79, -27, -22, 81, -35, -38, -41, 23,
	23, -42, 82, 81, 82, 86, -21, 82, 82, 82,
	71, -21, -22, 82, -42, 82, 82,
}

var yrDef = [...]int16{
	1, -2, 2, 3, 0, 5, 0, 0, 4, 0,
	16, 17, 18, 6, 7, 19, 0, 0, 10, 20,
	21, 12, 0, 22, 8, 0, 0, 0, 0, 11,
	23, 0, 0, 0, 13, 30, 0, 24, 0, 9,
	0, 31, 0, 25, 26, 0, 28, 29, 132, 133,
	134, 14, 69, 70, 71, -2, 80, 0, 0, 0,
	0, 0, 136, 137, 0, 139, 140, 141, 142, 143,
	145, 147, 149, 150, 0, 0, 163, 125, 126, 127,
	60, 68, 32, 50, 57, 27, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 124, 0, 0, 92, 93,
	69, -2, 0, 0, 0, 0, 0, 0, 0, 64,
	151, 160, 36, 34, 35, 94, 95, 72, 73, 74,
	75, 76, 77, 78, 79, 0, 156, 96, 97, 98,
	99, 100, 101, 152, 153, 154, 155, 157, 158, 159,
	161, 162, 81, 82, 0, 0, 0, 128, 0, 0,
	87, 88, 89, 0, 110, 103, 135, 0, 144, 0,
	0, 61, 0, 0, 65, -2, 33, 51, 52, 53,
	54, 55, 56, 58, 59, 90, 91, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 111, 116,
	121, 113, 114, 118, 123, 138, 146, 148, 62, 63,
	0, 37, 38, 39, 40, 41, 42, 43, 44, 47,
	0, 0, 130, 131, 0, 105, 129, 0, 85, 86,
	109, 0, 115, 0, 120, 0, 119, -2, 0, 0,
	0, 0, 0, 0, 107, 0, 112, 117, 122, 0,
	0, 0, 106, 0, 104, 0, 0, 45, 46, 48,
	0, 0, 108, 84, 0, 83, 49,
}

var yrTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 74, 61, 3,
	81, 82, 72, 70, 86, 71, 83, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 79, 3,
	3, 80, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 84, 73, 85, 60, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 77, 59, 78, 75,
}

var yrTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 62, 63, 64,
	65, 66, 67, 68, 69, 76,
}

var yrTok3 = [...]int8{
	0,
}

var yrErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yrDebug        = 0
	yrErrorVerbose = false
)

type yrLexer interface {
	Lex(lval *yrSymType) int
	Error(s string)
}

type yrParser interface {
	Parse(yrLexer) int
	Lookahead() int
}

type yrParserImpl struct {
	lval  yrSymType
	stack [yrInitialStackSize]yrSymType
	char  int
}

func (p *yrParserImpl) Lookahead() int {
	return p.char
}

func yrNewParser() yrParser {
	return &yrParserImpl{}
}

const yrFlag = -1000

func yrTokname(c int) string {
	if c >= 1 && c-1 < len(yrToknames) {
		if yrToknames[c-1] != "" {
			return yrToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yrStatname(s int) string {
	if s >= 0 && s < len(yrStatenames) {
		if yrStatenames[s] != "" {
			return yrStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yrErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yrErrorVerbose {
		return "syntax error"
	}

	for _, e := range yrErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yrTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yrPact[state])
	for tok := TOKSTART; tok-1 < len(yrToknames); tok++ {
		if n := base + tok; n >= 0 && n < yrLast && int(yrChk[int(yrAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yrDef[state] == -2 {
		i := 0
		for yrExca[i] != -1 || int(yrExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yrExca[i] >= 0; i += 2 {
			tok := int(yrExca[i])
			if tok < TOKSTART || yrExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yrExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yrTokname(tok)
	}
	return res
}

func yrlex1(lex yrLexer, lval *yrSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yrTok1[0])
		goto out
	}
	if char < len(yrTok1) {
		token = int(yrTok1[char])
		goto out
	}
	if char >= yrPrivate {
		if char < yrPrivate+len(yrTok2) {
			token = int(yrTok2[char-yrPrivate])
			goto out
		}
	}
	for i := 0; i < len(yrTok3); i += 2 {
		token = int(yrTok3[i+0])
		if token == char {
			token = int(yrTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yrTok2[1]) /* unknown char */
	}
	if yrDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yrTokname(token), uint(char))
	}
	return char, token
}

func yrParse(yrlex yrLexer) int {
	return yrNewParser().Parse(yrlex)
}

func (yrrcvr *yrParserImpl) Parse(yrlex yrLexer) int {
	var yrn int
	var yrVAL yrSymType
	var yrDollar []yrSymType
	_ = yrDollar // silence set and not used
	yrS := yrrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yrstate := 0
	yrrcvr.char = -1
	yrtoken := -1 // yrrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yrstate = -1
		yrrcvr.char = -1
		yrtoken = -1
	}()
	yrp := -1
	goto yrstack

ret0:
	return 0

ret1:
	return 1

yrstack:
	/* put a state and value onto the stack */
	if yrDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yrTokname(yrtoken), yrStatname(yrstate))
	}

	yrp++
	if yrp >= len(yrS) {
		nyys := make([]yrSymType, len(yrS)*2)
		copy(nyys, yrS)
		yrS = nyys
	}
	yrS[yrp] = yrVAL
	yrS[yrp].yys = yrstate

yrnewstate:
	yrn = int(yrPact[yrstate])
	if yrn <= yrFlag {
		goto yrdefault /* simple state */
	}
	if yrrcvr.char < 0 {
		yrrcvr.char, yrtoken = yrlex1(yrlex, &yrrcvr.lval)
	}
	yrn += yrtoken
	if yrn < 0 || yrn >= yrLast {
		goto yrdefault
	}
	yrn = int(yrAct[yrn])
	if int(yrChk[yrn]) == yrtoken { /* valid shift */
		yrrcvr.char = -1
		yrtoken = -1
		yrVAL = yrrcvr.lval
		yrstate = yrn
		if Errflag > 0 {
			Errflag--
		}
		goto yrstack
	}

yrdefault:
	/* default state action */
	yrn = int(yrDef[yrstate])
	if yrn == -2 {
		if yrrcvr.char < 0 {
			yrrcvr.char, yrtoken = yrlex1(yrlex, &yrrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yrExca[xi+0] == -1 && int(yrExca[xi+1]) == yrstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yrn = int(yrExca[xi+0])
			if yrn < 0 || yrn == yrtoken {
				break
			}
		}
		yrn = int(yrExca[xi+1])
		if yrn < 0 {
			goto ret0
		}
	}
	if yrn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yrlex.Error(yrErrorMessage(yrstate, yrtoken))
			Nerrs++
			if yrDebug >= 1 {
				__yyfmt__.Printf("%s", yrStatname(yrstate))
				__yyfmt__.Printf(" saw %s\n", yrTokname(yrtoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yrp >= 0 {
				yrn = int(yrPact[yrS[yrp].yys]) + yrErrCode
				if yrn >= 0 && yrn < yrLast {
					yrstate = int(yrAct[yrn]) /* simulate a shift of "error" */
					if int(yrChk[yrstate]) == yrErrCode {
						goto yrstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yrDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yrS[yrp].yys)
				}
				yrp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yrDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yrTokname(yrtoken))
			}
			if yrtoken == yrEofCode {
				goto ret1
			}
			yrrcvr.char = -1
			yrtoken = -1
			goto yrnewstate /* try again in the same state */
		}
	}

	/* reduction by production yrn */
	if yrDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yrn, yrStatname(yrstate))
	}

	yrnt := yrn
	yrpt := yrp
	_ = yrpt // guard against "declared and not used"

	yrp -= int(yrR2[yrn])
	// yrp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yrp+1 >= len(yrS) {
		nyys := make([]yrSymType, len(yrS)*2)
		copy(nyys, yrS)
		yrS = nyys
	}
	yrVAL = yrS[yrp+1]

	/* consult goto table to find next state */
	yrn = int(yrR1[yrn])
	yrg := int(yrPgo[yrn])
	yrj := yrg + yrS[yrp].yys + 1

	if yrj >= yrLast {
		yrstate = int(yrAct[yrg])
	} else {
		yrstate = int(yrAct[yrj])
		if int(yrChk[yrstate]) != -yrn {
			yrstate = int(yrAct[yrg])
		}
	}
	// dummy call; replaced with literal code
	switch yrnt {

	case 2:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:233
		{
			ruleSet := asLexer(yrlex).ruleSet
			ruleSet.Rules = append(ruleSet.Rules, yrDollar[2].rule)
		}
	case 3:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:238
		{
			ruleSet := asLexer(yrlex).ruleSet
			ruleSet.Imports = append(ruleSet.Imports, yrDollar[2].s)
		}
	case 4:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:243
		{
			ruleSet := asLexer(yrlex).ruleSet
			ruleSet.Includes = append(ruleSet.Includes, yrDollar[3].s)
		}
	case 5:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:248
		{

		}
	case 6:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:256
		{
			if err := validateAscii(yrDollar[2].s); err != nil {
				return asLexer(yrlex).setError(
					gyperror.InvalidAsciiError, err.Error())
			}

			yrVAL.s = yrDollar[2].s
		}
	case 7:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:269
		{
			lexer := asLexer(yrlex)

			// Forbid duplicate rules
			for _, r := range lexer.ruleSet.Rules {
				if yrDollar[3].s == r.Identifier {
					return lexer.setError(
						gyperror.DuplicateRuleError, `duplicate rule "%s"`, yrDollar[3].s)
				}
			}

			// Forbid any rule which matches our rules wildcard table. This ensures
			// the following is a syntax error:
			//
			// rule a { condition: true }
			// rule b { condition: any of (a*) }
			// rule a2 { condition: true }
			//
			// This must be a syntax error because the "a2" rule is defined _AFTER_
			// the (a*) expansion.
			for i, _ := range lexer.rule_wildcards {
				if strings.HasPrefix(yrDollar[3].s, i) {
					return lexer.setError(
						gyperror.UndefinedRuleIdentifierError,
						`rule identifier "%s" matches previously used wildcard rule set`, yrDollar[3].s)
				}
			}

			// The line number of the rule is the line number of the first
			// modifier....
			yrVAL.lineno = yrDollar[1].lineno

			// ... or the line number of the "rule" keyword if the rule doesn't
			// have any modifiers.
			if yrVAL.lineno == -1 {
				yrVAL.lineno = yrDollar[2].lineno
			}

			// Store the rule identifier for lookup to ensure rule references are
			// always defined.
			lexer.rules[yrDollar[3].s] = true

			yrVAL.rule = &ast.Rule{
				LineNo:     yrVAL.lineno,
				Global:     yrDollar[1].mod&ModGlobal == ModGlobal,
				Private:    yrDollar[1].mod&ModPrivate == ModPrivate,
				Identifier: yrDollar[3].s,
			}
		}
	case 8:
		yrDollar = yrS[yrpt-8 : yrpt+1]
//line parser/grammar.y:319
		{
			// Check for duplicate strings.
			m := make(map[string]bool)
			for _, str := range yrDollar[8].yss {
				ident := str.GetIdentifier()
				// Anonymous strings (no identifiers) are fine.
				if ident == "" {
					continue
				}
				if m[ident] {
					return asLexer(yrlex).setErrorWithLineNumber(
						gyperror.DuplicateStringError,
						str.GetLineNo(),
						`rule "%s": duplicate string identifier "%s"`, yrDollar[4].rule.Identifier, ident)
				}
				m[ident] = true
			}
			yrDollar[4].rule.Tags = yrDollar[5].ss
			yrDollar[4].rule.Meta = yrDollar[7].metas
			yrDollar[4].rule.Strings = yrDollar[8].yss
		}
	case 9:
		yrDollar = yrS[yrpt-11 : yrpt+1]
//line parser/grammar.y:341
		{
			yrDollar[4].rule.Condition = yrDollar[10].expr
			yrVAL.rule = yrDollar[4].rule

			// Clear the strings map for the next rule being parsed.
			asLexer(yrlex).strings = make(map[string]bool)
		}
	case 10:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:353
		{
			yrVAL.metas = []*ast.Meta{}
		}
	case 11:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:357
		{
			yrVAL.metas = yrDollar[3].metas
		}
	case 12:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:365
		{
			yrVAL.yss = []ast.String{}
		}
	case 13:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:369
		{
			yrVAL.yss = yrDollar[3].yss
		}
	case 14:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:377
		{
			yrVAL.expr = yrDollar[3].expr
		}
	case 15:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:385
		{
			yrVAL.mod = 0
			yrVAL.lineno = -1
		}
	case 16:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:390
		{
			yrVAL.mod = yrDollar[1].mod | yrDollar[2].mod

			if yrDollar[1].lineno == -1 {
				yrVAL.lineno = yrDollar[2].lineno
			} else {
				yrVAL.lineno = yrDollar[1].lineno
			}
		}
	case 17:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:404
		{
			yrVAL.mod = ModPrivate
			yrVAL.lineno = yrDollar[1].lineno
		}
	case 18:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:409
		{
			yrVAL.mod = ModGlobal
			yrVAL.lineno = yrDollar[1].lineno
		}
	case 19:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:418
		{
			yrVAL.ss = []string{}
		}
	case 20:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:422
		{
			yrVAL.ss = yrDollar[2].ss
		}
	case 21:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:430
		{
			yrVAL.ss = []string{yrDollar[1].s}
		}
	case 22:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:434
		{
			lexer := asLexer(yrlex)

			for _, tag := range yrDollar[1].ss {
				if tag == yrDollar[2].s {
					return lexer.setError(
						gyperror.DuplicateTagError, `duplicate tag "%s"`, yrDollar[2].s)
				}
			}

			yrVAL.ss = append(yrDollar[1].ss, yrDollar[2].s)
		}
	case 23:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:451
		{
			yrVAL.metas = []*ast.Meta{yrDollar[1].meta}
		}
	case 24:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:455
		{
			yrVAL.metas = append(yrDollar[1].metas, yrDollar[2].meta)
		}
	case 25:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:463
		{
			yrVAL.meta = &ast.Meta{
				Key:   yrDollar[1].s,
				Value: yrDollar[3].s,
			}
		}
	case 26:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:470
		{
			yrVAL.meta = &ast.Meta{
				Key:   yrDollar[1].s,
				Value: yrDollar[3].i64,
			}
		}
	case 27:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:477
		{
			yrVAL.meta = &ast.Meta{
				Key:   yrDollar[1].s,
				Value: -yrDollar[4].i64,
			}
		}
	case 28:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:484
		{
			yrVAL.meta = &ast.Meta{
				Key:   yrDollar[1].s,
				Value: true,
			}
		}
	case 29:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:491
		{
			yrVAL.meta = &ast.Meta{
				Key:   yrDollar[1].s,
				Value: false,
			}
		}
	case 30:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:502
		{
			lexer := asLexer(yrlex)
			lexer.strings[yrDollar[1].ys.GetIdentifier()] = true
			yrVAL.yss = []ast.String{yrDollar[1].ys}
		}
	case 31:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:508
		{
			lexer := asLexer(yrlex)
			lexer.strings[yrDollar[2].ys.GetIdentifier()] = true
			yrVAL.yss = append(yrDollar[1].yss, yrDollar[2].ys)
		}
	case 32:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:518
		{
			if err := validateUTF8(yrDollar[3].s); err != nil {
				return asLexer(yrlex).setError(
					gyperror.InvalidUTF8Error, err.Error())
			}
		}
	case 33:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line parser/grammar.y:525
		{
			yrVAL.ys = &ast.TextString{
				BaseString: ast.BaseString{
					Identifier: strings.TrimPrefix(yrDollar[1].s, "$"),
					LineNo:     yrDollar[1].lineno,
				},
				ASCII:          yrDollar[5].smod.modifiers&ModASCII != 0,
				Wide:           yrDollar[5].smod.modifiers&ModWide != 0,
				Nocase:         yrDollar[5].smod.modifiers&ModNocase != 0,
				Fullword:       yrDollar[5].smod.modifiers&ModFullword != 0,
				Private:        yrDollar[5].smod.modifiers&ModPrivate != 0,
				Base64:         yrDollar[5].smod.modifiers&ModBase64 != 0,
				Base64Wide:     yrDollar[5].smod.modifiers&ModBase64Wide != 0,
				Base64Alphabet: yrDollar[5].smod.Base64Alphabet,
				Xor:            yrDollar[5].smod.modifiers&ModXor != 0,
				XorMin:         yrDollar[5].smod.XorMin,
				XorMax:         yrDollar[5].smod.XorMax,
				Value:          yrDollar[3].s,
			}
		}
	case 34:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:546
		{
			yrVAL.ys = &ast.RegexpString{
				BaseString: ast.BaseString{
					Identifier: strings.TrimPrefix(yrDollar[1].s, "$"),
					LineNo:     yrDollar[1].lineno,
				},
				ASCII:    yrDollar[4].mod&ModASCII != 0,
				Wide:     yrDollar[4].mod&ModWide != 0,
				Nocase:   yrDollar[4].mod&ModNocase != 0,
				Fullword: yrDollar[4].mod&ModFullword != 0,
				Private:  yrDollar[4].mod&ModPrivate != 0,
				Regexp:   yrDollar[3].reg,
			}
		}
	case 35:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:561
		{
			yrVAL.ys = &ast.HexString{
				BaseString: ast.BaseString{
					Identifier: strings.TrimPrefix(yrDollar[1].s, "$"),
					LineNo:     yrDollar[1].lineno,
				},
				Private: yrDollar[4].mod&ModPrivate != 0,
				Tokens:  yrDollar[3].hexTokens,
			}
		}
	case 36:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:576
		{
			yrVAL.smod = stringModifiers{}
		}
	case 37:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:580
		{
			if yrDollar[1].smod.modifiers&yrDollar[2].smod.modifiers != 0 {
				return asLexer(yrlex).setError(
					gyperror.DuplicateModifierError, `duplicate modifier`)
			}

			yrDollar[1].smod.modifiers |= yrDollar[2].smod.modifiers

			if yrDollar[2].smod.modifiers&ModXor != 0 {
				yrDollar[1].smod.XorMin = yrDollar[2].smod.XorMin
				yrDollar[1].smod.XorMax = yrDollar[2].smod.XorMax
			}

			if yrDollar[2].smod.modifiers&(ModBase64|ModBase64Wide) != 0 {
				yrDollar[1].smod.Base64Alphabet = yrDollar[2].smod.Base64Alphabet
			}

			yrVAL.smod = yrDollar[1].smod
		}
	case 38:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:603
		{
			yrVAL.smod = stringModifiers{modifiers: ModWide}
		}
	case 39:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:604
		{
			yrVAL.smod = stringModifiers{modifiers: ModASCII}
		}
	case 40:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:605
		{
			yrVAL.smod = stringModifiers{modifiers: ModNocase}
		}
	case 41:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:606
		{
			yrVAL.smod = stringModifiers{modifiers: ModFullword}
		}
	case 42:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:607
		{
			yrVAL.smod = stringModifiers{modifiers: ModPrivate}
		}
	case 43:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:608
		{
			yrVAL.smod = stringModifiers{modifiers: ModBase64}
		}
	case 44:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:609
		{
			yrVAL.smod = stringModifiers{modifiers: ModBase64Wide}
		}
	case 45:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:611
		{
			if err := validateAscii(yrDollar[3].s); err != nil {
				return asLexer(yrlex).setError(
					gyperror.InvalidAsciiError, err.Error())
			}

			if len(yrDollar[3].s) != 64 {
				return asLexer(yrlex).setError(
					gyperror.InvalidStringModifierError,
					"length of base64 alphabet must be 64")
			}

			yrVAL.smod = stringModifiers{
				modifiers:      ModBase64,
				Base64Alphabet: yrDollar[3].s,
			}
		}
	case 46:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:629
		{
			if err := validateAscii(yrDollar[3].s); err != nil {
				return asLexer(yrlex).setError(
					gyperror.InvalidAsciiError, err.Error())
			}

			if len(yrDollar[3].s) != 64 {
				return asLexer(yrlex).setError(
					gyperror.InvalidStringModifierError,
					"length of base64 alphabet must be 64")
			}

			yrVAL.smod = stringModifiers{
				modifiers:      ModBase64Wide,
				Base64Alphabet: yrDollar[3].s,
			}
		}
	case 47:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:647
		{
			yrVAL.smod = stringModifiers{
				modifiers: ModXor,
				XorMin:    0,
				XorMax:    255,
			}
		}
	case 48:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:655
		{
			yrVAL.smod = stringModifiers{
				modifiers: ModXor,
				XorMin:    int32(yrDollar[3].i64),
				XorMax:    int32(yrDollar[3].i64),
			}
		}
	case 49:
		yrDollar = yrS[yrpt-6 : yrpt+1]
//line parser/grammar.y:663
		{
			lexer := asLexer(yrlex)

			if yrDollar[3].i64 < 0 {
				return lexer.setError(
					gyperror.InvalidStringModifierError,
					"lower bound for xor range exceeded (min: 0)")
			}

			if yrDollar[5].i64 > 255 {
				return lexer.setError(
					gyperror.InvalidStringModifierError,
					"upper bound for xor range exceeded (max: 255)")
			}

			if yrDollar[3].i64 > yrDollar[5].i64 {
				return lexer.setError(
					gyperror.InvalidStringModifierError,
					"xor lower bound exceeds upper bound")
			}

			yrVAL.smod = stringModifiers{
				modifiers: ModXor,
				XorMin:    int32(yrDollar[3].i64),
				XorMax:    int32(yrDollar[5].i64),
			}
		}
	case 50:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:695
		{
			yrVAL.mod = 0
		}
	case 51:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:699
		{
			yrVAL.mod = yrDollar[1].mod | yrDollar[2].mod
		}
	case 52:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:706
		{
			yrVAL.mod = ModWide
		}
	case 53:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:707
		{
			yrVAL.mod = ModASCII
		}
	case 54:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:708
		{
			yrVAL.mod = ModNocase
		}
	case 55:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:709
		{
			yrVAL.mod = ModFullword
		}
	case 56:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:710
		{
			yrVAL.mod = ModPrivate
		}
	case 57:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:716
		{
			yrVAL.mod = 0
		}
	case 58:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:720
		{
			yrVAL.mod = yrDollar[1].mod | yrDollar[2].mod
		}
	case 59:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:727
		{
			yrVAL.mod = ModPrivate
		}
	case 60:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:733
		{
			yrVAL.expr = &ast.Identifier{Identifier: yrDollar[1].s}
		}
	case 61:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:737
		{
			yrVAL.expr = &ast.MemberAccess{
				Container: yrDollar[1].expr,
				Member:    yrDollar[3].s,
			}
		}
	case 62:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:744
		{
			yrVAL.expr = &ast.Subscripting{
				Array: yrDollar[1].expr,
				Index: yrDollar[3].expr,
			}
		}
	case 63:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:751
		{
			yrVAL.expr = &ast.FunctionCall{
				Callable:  yrDollar[1].expr,
				Arguments: yrDollar[3].exprs,
				Builtin:   false,
			}
		}
	case 64:
		yrDollar = yrS[yrpt-0 : yrpt+1]
//line parser/grammar.y:763
		{
			yrVAL.exprs = []ast.Expression{}
		}
	case 65:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:767
		{
			yrVAL.exprs = yrDollar[1].exprs
		}
	case 66:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:774
		{
			yrVAL.exprs = []ast.Expression{yrDollar[1].expr}
		}
	case 67:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:778
		{
			yrVAL.exprs = append(yrDollar[1].exprs, yrDollar[3].expr)
		}
	case 68:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:786
		{
			yrVAL.reg = yrDollar[1].reg
		}
	case 69:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:794
		{
			yrVAL.expr = yrDollar[1].expr
		}
	case 70:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:802
		{
			yrVAL.expr = ast.KeywordTrue
		}
	case 71:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:806
		{
			yrVAL.expr = ast.KeywordFalse
		}
	case 72:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:810
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpMatches,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].reg},
			}
		}
	case 73:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:817
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpContains,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 74:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:824
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpIContains,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 75:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:831
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpStartsWith,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 76:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:838
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpIStartsWith,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 77:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:845
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpEndsWith,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 78:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:852
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpIEndsWith,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 79:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:859
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpIEquals,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 80:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:866
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "$")
			// Exclude anonymous ($) strings.
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringIdentifier{
				Identifier: identifier,
			}
		}
	case 81:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:882
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "$")
			// Exclude anonymous ($) strings.
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringIdentifier{
				Identifier: identifier,
				At:         yrDollar[3].expr,
			}
		}
	case 82:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:899
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "$")
			// Exclude anonymous ($) strings.
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringIdentifier{
				Identifier: identifier,
				In:         yrDollar[3].rng,
			}
		}
	case 83:
		yrDollar = yrS[yrpt-9 : yrpt+1]
//line parser/grammar.y:916
		{
			yrVAL.expr = &ast.ForIn{
				Quantifier: yrDollar[2].expr,
				Variables:  yrDollar[3].ss,
				Iterator:   yrDollar[5].node,
				Condition:  yrDollar[8].expr,
			}
		}
	case 84:
		yrDollar = yrS[yrpt-8 : yrpt+1]
//line parser/grammar.y:925
		{
			yrVAL.expr = &ast.ForOf{
				Quantifier: yrDollar[2].expr,
				Strings:    yrDollar[4].node,
				Condition:  yrDollar[7].expr,
			}
		}
	case 85:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line parser/grammar.y:933
		{
			yrVAL.expr = &ast.Of{
				Quantifier: yrDollar[1].expr,
				Strings:    yrDollar[3].node,
				In:         yrDollar[5].rng,
			}
		}
	case 86:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line parser/grammar.y:941
		{
			yrVAL.expr = &ast.Of{
				Quantifier: yrDollar[1].expr,
				Strings:    yrDollar[3].node,
				At:         yrDollar[5].expr,
			}
		}
	case 87:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:949
		{
			yrVAL.expr = &ast.Of{
				Quantifier: yrDollar[1].expr,
				Strings:    yrDollar[3].node,
			}
		}
	case 88:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:956
		{
			yrVAL.expr = &ast.Of{
				Quantifier: yrDollar[1].expr,
				Rules:      yrDollar[3].node,
			}
		}
	case 89:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:963
		{
			yrVAL.expr = &ast.Of{
				Quantifier:  yrDollar[1].expr,
				TextStrings: yrDollar[3].ss,
			}
		}
	case 90:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:970
		{
			yrVAL.expr = &ast.Of{
				Quantifier: &ast.Percentage{yrDollar[1].expr},
				Strings:    yrDollar[4].node,
			}
		}
	case 91:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:977
		{
			yrVAL.expr = &ast.Of{
				Quantifier: &ast.Percentage{yrDollar[1].expr},
				Rules:      yrDollar[4].node,
			}
		}
	case 92:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:984
		{
			yrVAL.expr = &ast.Not{yrDollar[2].expr}
		}
	case 93:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:988
		{
			yrVAL.expr = &ast.Defined{yrDollar[2].expr}
		}
	case 94:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:992
		{
			yrVAL.expr = operation(ast.OpAnd, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 95:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:996
		{
			yrVAL.expr = operation(ast.OpOr, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 96:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1000
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpLessThan,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 97:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1007
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpGreaterThan,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 98:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1014
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpLessOrEqual,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 99:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1021
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpGreaterOrEqual,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 100:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1028
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpEqual,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 101:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1035
		{
			yrVAL.expr = &ast.Operation{
				Operator: ast.OpNotEqual,
				Operands: []ast.Expression{yrDollar[1].expr, yrDollar[3].expr},
			}
		}
	case 102:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1042
		{
			yrVAL.expr = yrDollar[1].expr
		}
	case 103:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1046
		{
			yrVAL.expr = &ast.Group{yrDollar[2].expr}
		}
	case 104:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1054
		{
			yrVAL.node = &ast.Enum{Values: yrDollar[2].exprs}
		}
	case 105:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1058
		{
			yrVAL.node = yrDollar[1].rng
		}
	case 106:
		yrDollar = yrS[yrpt-5 : yrpt+1]
//line parser/grammar.y:1066
		{
			if start, ok := yrDollar[2].expr.(*ast.LiteralInteger); ok {
				if end, ok := yrDollar[4].expr.(*ast.LiteralInteger); ok {
					if start.Value > end.Value {
						lexer := asLexer(yrlex)
						return lexer.setError(
							gyperror.InvalidValueError,
							"lower bound must be less than upper bound")
					}
				}
			}

			if v, ok := yrDollar[2].expr.(*ast.Minus); ok {
				if _, ok := v.Expression.(*ast.LiteralInteger); ok {
					lexer := asLexer(yrlex)
					return lexer.setError(
						gyperror.InvalidValueError,
						"lower bound can not be negative")
				}
			}

			if v, ok := yrDollar[4].expr.(*ast.Minus); ok {
				if _, ok := v.Expression.(*ast.LiteralInteger); ok {
					lexer := asLexer(yrlex)
					return lexer.setError(
						gyperror.InvalidValueError,
						"upper bound can not be negative")
				}
			}

			yrVAL.rng = &ast.Range{
				Start: yrDollar[2].expr,
				End:   yrDollar[4].expr,
			}
		}
	case 107:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1106
		{
			yrVAL.exprs = []ast.Expression{yrDollar[1].expr}
		}
	case 108:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1110
		{
			yrVAL.exprs = append(yrDollar[1].exprs, yrDollar[3].expr)
		}
	case 109:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1118
		{
			yrVAL.node = &ast.Enum{Values: yrDollar[2].exprs}
		}
	case 110:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1122
		{
			lexer := asLexer(yrlex)
			if len(lexer.strings) == 0 {
				return lexer.setError(
					gyperror.UndefinedStringIdentifierError,
					`undefined string identifier: %s`, ast.KeywordThem)
			}
			yrVAL.node = ast.KeywordThem
		}
	case 111:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1136
		{
			yrVAL.exprs = []ast.Expression{yrDollar[1].si}
		}
	case 112:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1140
		{
			yrVAL.exprs = append(yrDollar[1].exprs, yrDollar[3].si)
		}
	case 113:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1148
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "$")
			lexer := asLexer(yrlex)
			// Anonymous strings ($) in string enumerations are an error.
			if _, ok := lexer.strings[identifier]; !ok || identifier == "" {
				return lexer.setError(
					gyperror.UndefinedStringIdentifierError,
					`undefined string identifier: %s`, yrDollar[1].s)
			}
			yrVAL.si = &ast.StringIdentifier{
				Identifier: identifier,
			}
		}
	case 114:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1162
		{
			identifier := strings.TrimSuffix(yrDollar[1].s, "*")
			lexer := asLexer(yrlex)
			// There must be at least one defined string.
			if len(identifier) == 0 && len(lexer.strings) == 0 {
				return lexer.setError(
					gyperror.UndefinedStringIdentifierError,
					`undefined string identifier: %s`, yrDollar[1].s)
			}

			// There must be at least one string that will match the wildcard.
			identifier = strings.TrimPrefix(identifier, "$")
			match := false
			for s, _ := range lexer.strings {
				if strings.HasPrefix(s, identifier) {
					match = true
					break
				}
			}
			if !match {
				return lexer.setError(
					gyperror.UndefinedStringIdentifierError,
					`undefined string identifier: %s`, yrDollar[1].s)
			}
			// Can't use "identifier" here as that has the asterisk stripped already.
			yrVAL.si = &ast.StringIdentifier{
				Identifier: strings.TrimPrefix(yrDollar[1].s, "$"),
			}
		}
	case 115:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1196
		{
			yrVAL.node = &ast.Enum{Values: yrDollar[2].exprs}
		}
	case 116:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1204
		{
			yrVAL.exprs = []ast.Expression{yrDollar[1].ident}
		}
	case 117:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1208
		{
			yrVAL.exprs = append(yrDollar[1].exprs, yrDollar[3].ident)
		}
	case 118:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1216
		{
			lexer := asLexer(yrlex)
			match := false
			for r, _ := range lexer.rules {
				if r == yrDollar[1].s {
					match = true
					break
				}
			}
			if !match {
				return lexer.setError(
					gyperror.UndefinedRuleIdentifierError,
					`undefined rule identifier: %s`, yrDollar[1].s)
			}

			yrVAL.ident = &ast.Identifier{Identifier: yrDollar[1].s}
		}
	case 119:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:1234
		{
			// There must be at least one rule which matches this wildcard
			lexer := asLexer(yrlex)
			match := false
			for r, _ := range lexer.rules {
				if strings.HasPrefix(r, yrDollar[1].s) {
					match = true
					break
				}
			}
			if !match {
				return lexer.setError(
					gyperror.UndefinedRuleIdentifierError,
					`undefined rule identifier: %s`, yrDollar[1].s+"*")
			}

			// Store the identifier without the asterisk for lookup later. When a
			// new rule is created it must not be a prefix match for anything in
			// this table.
			lexer.rule_wildcards[yrDollar[1].s] = true
			yrVAL.ident = &ast.Identifier{Identifier: yrDollar[1].s + "*"}
		}
	case 120:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1261
		{
			yrVAL.ss = yrDollar[2].ss
		}
	case 121:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1269
		{
			yrVAL.ss = []string{yrDollar[1].s}
		}
	case 122:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1273
		{
			yrVAL.ss = append(yrDollar[1].ss, yrDollar[3].s)
		}
	case 123:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1281
		{
			yrVAL.s = yrDollar[1].s
		}
	case 124:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1289
		{
			switch v := yrDollar[1].expr.(type) {
			case *ast.Minus:
				if i, ok := v.Expression.(*ast.LiteralInteger); ok {
					lexer := asLexer(yrlex)
					return lexer.setError(
						gyperror.InvalidValueError,
						`invalid value in condition: -%d`, i.Value)
				}
			case *ast.LiteralString:
				lexer := asLexer(yrlex)
				return lexer.setError(
					gyperror.InvalidValueError,
					`invalid value in condition: "%s"`, v.Value)
			case *ast.LiteralRegexp:
				lexer := asLexer(yrlex)
				return lexer.setError(
					gyperror.InvalidValueError,
					`invalid value in condition: /%s/`, v.Value)
			case *ast.LiteralFloat:
				lexer := asLexer(yrlex)
				return lexer.setError(
					gyperror.InvalidValueError,
					`invalid value in condition: %f`, v.Value)
			}
			yrVAL.expr = yrDollar[1].expr
		}
	case 125:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1317
		{
			yrVAL.expr = ast.KeywordAll
		}
	case 126:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1321
		{
			yrVAL.expr = ast.KeywordAny
		}
	case 127:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1325
		{
			yrVAL.expr = ast.KeywordNone
		}
	case 128:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1333
		{
			yrVAL.ss = []string{yrDollar[1].s}
		}
	case 129:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1337
		{
			yrVAL.ss = append(yrDollar[1].ss, yrDollar[3].s)
		}
	case 130:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1344
		{
			yrVAL.node = yrDollar[1].expr
		}
	case 131:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1348
		{
			yrVAL.node = yrDollar[1].node
		}
	case 132:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1355
		{
			yrVAL.i64 = yrDollar[1].i64
		}
	case 133:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1359
		{
			yrVAL.i64 = yrDollar[1].i64
		}
	case 134:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1363
		{
			yrVAL.i64 = yrDollar[1].i64
		}
	case 135:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1369
		{
			yrVAL.expr = &ast.Group{yrDollar[2].expr}
		}
	case 136:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1373
		{
			yrVAL.expr = ast.KeywordFilesize
		}
	case 137:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1377
		{
			yrVAL.expr = ast.KeywordEntrypoint
		}
	case 138:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:1381
		{
			yrVAL.expr = &ast.FunctionCall{
				Callable:  &ast.Identifier{Identifier: yrDollar[1].s},
				Arguments: []ast.Expression{yrDollar[3].expr},
				Builtin:   true,
			}
		}
	case 139:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1389
		{
			yrVAL.expr = &ast.LiteralInteger{yrDollar[1].i64, 10}
		}
	case 140:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1393
		{
			yrVAL.expr = &ast.LiteralInteger{yrDollar[1].i64, 16}
		}
	case 141:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1397
		{
			yrVAL.expr = &ast.LiteralInteger{yrDollar[1].i64, 8}
		}
	case 142:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1401
		{
			yrVAL.expr = &ast.LiteralFloat{yrDollar[1].f64}
		}
	case 143:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1405
		{
			if err := validateUTF8(yrDollar[1].s); err != nil {
				return asLexer(yrlex).setError(
					gyperror.InvalidUTF8Error, err.Error())
			}

			yrVAL.expr = &ast.LiteralString{yrDollar[1].s}
		}
	case 144:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1414
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "#")
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringCount{
				Identifier: identifier,
				In:         yrDollar[3].rng,
			}
		}
	case 145:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1430
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "#")
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringCount{
				Identifier: identifier,
			}
		}
	case 146:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:1445
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "@")
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringOffset{
				Identifier: identifier,
				Index:      yrDollar[3].expr,
			}
		}
	case 147:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1461
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "@")
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringOffset{
				Identifier: identifier,
			}
		}
	case 148:
		yrDollar = yrS[yrpt-4 : yrpt+1]
//line parser/grammar.y:1476
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "!")
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringLength{
				Identifier: identifier,
				Index:      yrDollar[3].expr,
			}
		}
	case 149:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1492
		{
			identifier := strings.TrimPrefix(yrDollar[1].s, "!")
			if identifier != "" {
				lexer := asLexer(yrlex)
				if _, ok := lexer.strings[identifier]; !ok {
					return lexer.setError(
						gyperror.UndefinedStringIdentifierError,
						`undefined string identifier: %s`, yrDollar[1].s)
				}
			}
			yrVAL.expr = &ast.StringLength{
				Identifier: strings.TrimPrefix(yrDollar[1].s, "!"),
			}
		}
	case 150:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1507
		{
			yrVAL.expr = yrDollar[1].expr
		}
	case 151:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:1511
		{
			yrVAL.expr = &ast.Minus{yrDollar[2].expr}
		}
	case 152:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1515
		{
			yrVAL.expr = operation(ast.OpAdd, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 153:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1519
		{
			yrVAL.expr = operation(ast.OpSub, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 154:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1523
		{
			yrVAL.expr = operation(ast.OpMul, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 155:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1527
		{
			yrVAL.expr = operation(ast.OpDiv, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 156:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1531
		{
			yrVAL.expr = operation(ast.OpMod, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 157:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1535
		{
			yrVAL.expr = operation(ast.OpBitXor, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 158:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1539
		{
			yrVAL.expr = operation(ast.OpBitAnd, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 159:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1543
		{
			yrVAL.expr = operation(ast.OpBitOr, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 160:
		yrDollar = yrS[yrpt-2 : yrpt+1]
//line parser/grammar.y:1547
		{
			yrVAL.expr = &ast.BitwiseNot{yrDollar[2].expr}
		}
	case 161:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1551
		{
			yrVAL.expr = operation(ast.OpShiftLeft, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 162:
		yrDollar = yrS[yrpt-3 : yrpt+1]
//line parser/grammar.y:1555
		{
			yrVAL.expr = operation(ast.OpShiftRight, yrDollar[1].expr, yrDollar[3].expr)
		}
	case 163:
		yrDollar = yrS[yrpt-1 : yrpt+1]
//line parser/grammar.y:1559
		{
			yrVAL.expr = yrDollar[1].reg
		}
	}
	goto yrstack /* stack new state and value */
}
